window.JR={};
JR.steps=[{name:'选材',hours:.15,people:1,reserved:.15},{name:'浸泡处理',hours:.25,people:1,reserved:.15},{name:'剪裁',hours:1,people:2,reserved:.30},{name:'烙烫拼贴',hours:2,people:3,reserved:.40},{name:'装裱',hours:.8,people:1,reserved:.50},{name:'质检',hours:.15,people:1,reserved:.10},{name:'包装',hours:.15,people:1,reserved:.10}];
JR.seed=()=>({version:1,orders:[{id:'JR-001',name:'鹤舞东方 · 芦苇画礼赠',customer:'文旅采购方（示例）',quantity:100,price:800,due:30,deposit:40,material:300,labor:240,other:40,spec:'40 × 60 cm · 双鹤主题 · 独立礼盒',text:'100件芦苇画，30天交付，预付款40%。单价与成本为可编辑的补充演示假设。',status:'生产中',completed:0,depositReceived:false,tailReceived:false}],settings:{cash:8000,safety:5000},materials:[],logs:[]});
JR.scenario=()=>({extra:0,dueShift:0,materialRise:0,tailDelay:0,purchaseWeek:2,batchPayment:false});
JR.money=n=>new Intl.NumberFormat('zh-CN',{maximumFractionDigits:0}).format(Math.round(n));
JR.date=d=>`第 ${Math.ceil(d)} 天`;
JR.escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
JR.plan=function(orders,scenario=JR.scenario()){
 const active=orders.filter(o=>o.status!=='待确认');const available=JR.steps.map((s,i)=>(s.people+(i===4?scenario.extra:0))*6*(1-s.reserved));
 const ready=JR.steps.map(()=>0),loads=JR.steps.map(()=>0);const results=[];
 [...active].sort((a,b)=>a.due-b.due).forEach(o=>{const jobs=[],stepRanges=JR.steps.map(()=>({start:Infinity,end:0}));for(let q=0;q<o.quantity;q+=20){let previous=0;const size=Math.min(20,o.quantity-q);JR.steps.forEach((step,i)=>{const start=Math.max(previous,ready[i]),duration=size*step.hours/available[i],end=start+duration;ready[i]=end;previous=end;loads[i]+=size*step.hours;stepRanges[i].start=Math.min(stepRanges[i].start,start);stepRanges[i].end=Math.max(stepRanges[i].end,end);jobs.push({step:i,start,end,size})})}const finish=Math.ceil(Math.max(...stepRanges.map(s=>s.end)));results.push({id:o.id,finish,due:Math.max(1,o.due+scenario.dueShift),late:Math.max(0,finish-Math.max(1,o.due+scenario.dueShift)),hours:o.quantity*4.5,ranges:stepRanges,jobs})});
 const deadline=active.length?Math.max(...active.map(o=>Math.max(1,o.due+scenario.dueShift))):30;const stages=JR.steps.map((s,i)=>({...s,people:s.people+(i===4?scenario.extra:0),demand:loads[i],capacity:available[i]*deadline,load:loads[i]/(available[i]*deadline)*100,available:available[i]}));const bottleneck=[...stages].sort((a,b)=>b.load-a.load)[0];return {orders:results,stages,bottleneck,deadline,hours:loads.reduce((a,b)=>a+b,0),finish:Math.ceil(Math.max(0,...ready)),available};
};
JR.cashflow=function(orders,settings,scenario=JR.scenario()){
 const plan=JR.plan(orders,scenario),active=orders.filter(o=>o.status!=='待确认');const events=[];let totalCost=0,totalRevenue=0;
 active.forEach(o=>{const p=plan.orders.find(x=>x.id===o.id),amount=o.quantity*o.price,material=o.quantity*o.material*(1+scenario.materialRise/100),extraLabor=scenario.extra*200*p.finish,labor=o.quantity*o.labor+extraLabor,other=o.quantity*o.other,tail=amount*(1-o.deposit/100),deposit=amount*o.deposit/100,delivery=Math.max(p.finish,p.due),tailDay=delivery+scenario.tailDelay,tailWeek=Math.ceil(tailDay/7),laborWeeks=Math.max(1,Math.ceil(p.finish/7));totalCost+=material+labor+other;totalRevenue+=amount;
 events.push({order:o.id,week:1,type:'in',name:'客户预付款',amount:deposit});events.push({order:o.id,week:scenario.purchaseWeek,type:'out',name:'材料采购',amount:material});for(let w=1;w<=laborWeeks;w++)events.push({order:o.id,week:w,type:'out',name:'制作人工',amount:labor/laborWeeks});events.push({order:o.id,week:Math.ceil(delivery/7),type:'out',name:'包装物流等',amount:other});if(scenario.batchPayment){events.push({order:o.id,week:Math.max(1,Math.ceil(delivery/14)),type:'in',name:'协商阶段回款（假设）',amount:tail/2});events.push({order:o.id,week:tailWeek,type:'in',name:'剩余尾款',amount:tail/2})}else events.push({order:o.id,week:tailWeek,type:'in',name:'交付尾款',amount:tail});
 });
 let balance=settings.cash;const weeks=Array.from({length:8},(_,i)=>{const week=i+1,items=events.filter(e=>e.week===week),income=items.filter(e=>e.type==='in').reduce((a,e)=>a+e.amount,0),expense=items.filter(e=>e.type==='out').reduce((a,e)=>a+e.amount,0),start=balance;balance+=income-expense;return {week,start,income,expense,balance,items,gap:Math.max(0,settings.safety-balance)}});const min=Math.min(settings.cash,...weeks.map(w=>w.balance)),gap=Math.max(0,settings.safety-min),shortage=Math.max(0,-min),first=weeks.find(w=>w.gap>0);return {plan,weeks,events,min,gap,shortage,first:settings.cash<settings.safety?0:first?.week||null,duration:weeks.filter(w=>w.gap>0).length,profit:totalRevenue-totalCost,totalRevenue,totalCost,afterHorizon:events.filter(e=>e.week>8),balance};
};
JR.parse=function(text){const result={};const fields={quantity:/(\d+)\s*件/,price:/单价\s*[:：]?\s*(\d+(?:\.\d+)?)\s*元?/,due:/(\d+)\s*天(?:内)?(?:交付|交货)|交期\s*[:：]?\s*(\d+)\s*天/,deposit:/(?:预付款|预付|定金)\s*[:：]?\s*(\d+(?:\.\d+)?)\s*%/};Object.entries(fields).forEach(([key,re])=>{const m=text.match(re);if(m)result[key]=Number(m[1]||m[2])});return result};
JR.icons={home:'<path d="m3 11 9-8 9 8M5 10v11h5v-7h4v7h5V10"/>',orders:'<path d="M5 3h14v18H5ZM8 8h8m-8 4h8m-8 4h5"/>',craft:'<circle cx="12" cy="12" r="4"/><path d="m9 2-1 3-3 1-3 3 2 3-2 3 3 3 3 1 1 3h6l1-3 3-1 3-3-2-3 2-3-3-3-3-1-1-3Z"/>',cash:'<path d="M4 21V12h3v9m4 0V7h3v14m4 0V3h3v18"/>',folder:'<path d="M3 6V3h7l3 3h8v15H3Z"/>',arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',coin:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v13c0 4 16 4 16 0V5M4 11c0 4 16 4 16 0"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v7h5"/>',cart:'<path d="M2 3h3l3 13h11l3-10H6M9 21h1m8 0h1"/>',check:'<path d="m4 12 5 5L21 4"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/>'};
JR.icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${JR.icons[n]||JR.icons.orders}</svg>`;
